### Download imputed data from MICHIGAN SERVER

#22 valid VCF file(s) found.

#Samples: 9062
#Chromosomes: 1 10 11 12 13 14 15 16 17 18 19 2 20 21 22 3 4 5 6 7 8 9
#SNPs: 578427
#Chunks: 154
#Datatype: unphased
#Build: hg19
#Reference Panel: apps@1000g-phase-3-v5 (hg19)
#Population: eur
#Phasing: eagle
#Mode: imputation

wget https://imputationserver.sph.umich.edu/share/results/7674802769cc812ce184a8ebc908ef7b/qcreport.html

wget https://imputationserver.sph.umich.edu/share/results/a554d8e59c56c0268b9ae42b0a799a36/snps-excluded.txt
wget https://imputationserver.sph.umich.edu/share/results/952381fb8103f4e5c17fe2f52519c6cb/typed-only.txt


wget https://imputationserver.sph.umich.edu/share/results/6580e71552d3dbf6a0e06bb99c5e2c6d/chr_1.zip
wget https://imputationserver.sph.umich.edu/share/results/7474979a58ff338c58de6a8a7bf0c0e0/chr_10.zip
wget https://imputationserver.sph.umich.edu/share/results/97010bf44288d04eb7c8beb86d0ef76a/chr_11.zip
wget https://imputationserver.sph.umich.edu/share/results/7de4c03fd04033fa7a6071551438fd47/chr_12.zip
wget https://imputationserver.sph.umich.edu/share/results/7d6a03cfca7f0222291153eefaf60718/chr_13.zip
wget https://imputationserver.sph.umich.edu/share/results/836548d9c9dad6c3063ae6ce8b563e72/chr_14.zip
wget https://imputationserver.sph.umich.edu/share/results/972e4f707f547a275fe4c49b3dc6ec8c/chr_15.zip
wget https://imputationserver.sph.umich.edu/share/results/fe179c6cfc1ce36643fe56d872f74e3e/chr_16.zip
wget https://imputationserver.sph.umich.edu/share/results/e816e816a021bfd52ce7f7705441a8d8/chr_17.zip
wget https://imputationserver.sph.umich.edu/share/results/c14da406fbdf1082a3f39993294f39d8/chr_18.zip
wget https://imputationserver.sph.umich.edu/share/results/fc02e974eb2622096b4aac91a4e43511/chr_19.zip
wget https://imputationserver.sph.umich.edu/share/results/3f56980e21c6027773584261cc49e2a0/chr_2.zip
wget https://imputationserver.sph.umich.edu/share/results/6253e7091a0e28dd0bcb26925238d536/chr_20.zip
wget https://imputationserver.sph.umich.edu/share/results/732f5f21d9328d3355975ec112efd954/chr_21.zip
wget https://imputationserver.sph.umich.edu/share/results/b3618a07a8d6d44b4a570d782d6a8506/chr_22.zip
wget https://imputationserver.sph.umich.edu/share/results/472b4647d13e936b12fa642dfed82793/chr_3.zip
wget https://imputationserver.sph.umich.edu/share/results/4f5e3e906820bf4b3bfc8ea16c924441/chr_4.zip
wget https://imputationserver.sph.umich.edu/share/results/d75a1387582da8d1f7863d7ac8e9ae3e/chr_5.zip
wget https://imputationserver.sph.umich.edu/share/results/35549476d3292902c90af06d0fa5bf94/chr_6.zip
wget https://imputationserver.sph.umich.edu/share/results/4a895099d12c064060a67c2e478093cb/chr_7.zip
wget https://imputationserver.sph.umich.edu/share/results/b77614a57731b758303a713d53359d56/chr_8.zip
wget https://imputationserver.sph.umich.edu/share/results/ce4bbf5cb8aed39c8775ad8c5d80c26/chr_9.zip


wget https://imputationserver.sph.umich.edu/share/results/6ea948b8a2d46a12c5350f6ef529be36/chr_1.log
wget https://imputationserver.sph.umich.edu/share/results/2d08a89b40aeeedd95418047e978d950/chr_10.log
wget https://imputationserver.sph.umich.edu/share/results/e5e1765305af36c2fe23cab88ba6c78c/chr_11.log
wget https://imputationserver.sph.umich.edu/share/results/f96f94c8dad9f325d7d845dbcec0fb09/chr_12.log
wget https://imputationserver.sph.umich.edu/share/results/790282f76c4157e87fbf473759feb7d4/chr_13.log
wget https://imputationserver.sph.umich.edu/share/results/e3069e58946e40c0cdf1b737938fbb64/chr_14.log
wget https://imputationserver.sph.umich.edu/share/results/cbd901d7ad75cbabc3d2e2ba9cb7717b/chr_15.log
wget https://imputationserver.sph.umich.edu/share/results/6a0c76547819a2ae63fef2c6f9e8ef69/chr_16.log
wget https://imputationserver.sph.umich.edu/share/results/7d31d19c07822a873d7ee7427ccc58a8/chr_17.log
wget https://imputationserver.sph.umich.edu/share/results/b38a9774feb0690f33f0350a7e51ca5a/chr_18.log
wget https://imputationserver.sph.umich.edu/share/results/ef9bddfe8938dff98b08ce30cce615d2/chr_19.log
wget https://imputationserver.sph.umich.edu/share/results/5356b464b83d201b77aa78671ce3e36d/chr_2.log
wget https://imputationserver.sph.umich.edu/share/results/bbe9428a3ff9a6b1f43d629f21f0a03e/chr_20.log
wget https://imputationserver.sph.umich.edu/share/results/dff2ac4a9279082c817f7504b852b747/chr_21.log
wget https://imputationserver.sph.umich.edu/share/results/332586c59f36ac0a256ca07969680902/chr_22.log
wget https://imputationserver.sph.umich.edu/share/results/69d6e457d06d763d63a796e2fb4dd5bd/chr_3.log
wget https://imputationserver.sph.umich.edu/share/results/3668eda6b88545d7a20f55e24e92e1a8/chr_4.log
wget https://imputationserver.sph.umich.edu/share/results/2941260240dfcaeaf50b403bae256ece/chr_5.log
wget https://imputationserver.sph.umich.edu/share/results/10e5a7b5010b27dfc0be0e3997ec7c59/chr_6.log
wget https://imputationserver.sph.umich.edu/share/results/d5ba407555161a7e18b0301b18513434/chr_7.log
wget https://imputationserver.sph.umich.edu/share/results/487fa3ff88daa099a77aa84e60656150/chr_8.log
wget https://imputationserver.sph.umich.edu/share/results/81d0bd41daa45db2c0ac36f5c48c41ec/chr_9.log
